"""add status to chatmessage

Revision ID: 51bada66c148
Revises: bd7855c7fd65
Create Date: 2026-08-30 19:47:08.371285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bada66c148'
down_revision: Union[str, Sequence[str], None] = 'bd7855c7fd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.add_column('chat_messages', sa.Column(
        'status', 
        sa.String(), 
        server_default='completed', 
        nullable=False
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'status')
    # ### end Alembic commands ###
