"""add is_pinned to chat_sessions

Revision ID: 617f8247a73f
Revises: 9a92666b5329
Create Date: 2026-09-11 21:29:15.996021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617f8247a73f'
down_revision: Union[str, Sequence[str], None] = '9a92666b5329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows so this NOT NULL add doesn't fail.
    op.add_column(
        'chat_sessions',
        sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('chat_sessions', 'is_pinned', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_pinned')
    # ### end Alembic commands ###
