"""add toc column to documents

Revision ID: 93d71060aea7
Revises: d7a2401ba54a
Create Date: 2026-08-15 10:41:37.256657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d71060aea7'
down_revision: Union[str, Sequence[str], None] = 'd7a2401ba54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('toc', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'toc')
    # ### end Alembic commands ###
