"""add scope_type and document_ids to chat_sessions

Revision ID: 9a92666b5329
Revises: d6d0250e4b7a
Create Date: 2026-09-06 14:35:42.171720

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a92666b5329"
down_revision: str | Sequence[str] | None = "d6d0250e4b7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: server_default values added by hand (autogenerate omitted them) so
    # the 33 pre-existing chat_sessions rows can satisfy the new NOT NULL
    # columns without a manual backfill step.
    chat_scope_enum = sa.Enum(
        "THIS_DOCUMENT", "SELECTED_DOCUMENTS", "ALL_DOCUMENTS", name="chatscope"
    )
    chat_scope_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "chat_sessions",
        sa.Column(
            "scope_type",
            chat_scope_enum,
            nullable=False,
            server_default="ALL_DOCUMENTS",
        ),
    )
    op.add_column(
        "chat_sessions",
        sa.Column("document_ids", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "document_ids")
    op.drop_column("chat_sessions", "scope_type")
    sa.Enum(name="chatscope").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
