"""add document_ids to chat_messages

Revision ID: d6d0250e4b7a
Revises: 51bada66c148
Create Date: 2026-09-02 14:57:46.330118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d0250e4b7a'
down_revision: Union[str, Sequence[str], None] = '51bada66c148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('document_ids', sa.JSON(), server_default='[]', nullable=False))
    op.drop_index(op.f('ix_chat_messages_seq'), table_name='chat_messages')
    op.create_unique_constraint(None, 'chat_messages', ['seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='unique')
    op.create_index(op.f('ix_chat_messages_seq'), 'chat_messages', ['seq'], unique=True)
    op.drop_column('chat_messages', 'document_ids')
    # ### end Alembic commands ###
